// Local HLS fixture server for the W0.3 harness.
//
// WHY THIS FILE EXISTS: e2e/smoke.mjs downloads from a public site -> depends on the network, and
// **has no 403 gate**, so it can never measure whether the hotlink-bypass feature actually works.
// This server serves exactly the tiny 10-segment HLS stream under e2e/fixtures/hls/ and returns
// **403 when Referer is missing** -> turns "does the spoof actually apply" into something OBSERVABLE.
//
// MEASURED ON REAL EDGE (probe 2026-07-17), don't re-investigate:
// - The extension CAN fetch http://127.0.0.1:PORT, no CORS header needed (host_permissions covers
//   it), and it isn't blocked by mixed-content (127.0.0.1/localhost is a "potentially trustworthy"
//   origin).
// - A bare fetch from the extension sends NEITHER Referer NOR Origin -> the "403 if Referer missing"
//   gate cleanly distinguishes "spoofed" from "not spoofed".
// - DNR requestDomains MATCHES an IP-form host ('127.0.0.1'), and '127.0.0.1' vs 'localhost' are TWO
//   SEPARATE hosts -> used as a trick to build the "segment on a different host than the manifest"
//   scenario (§2.4).

import { createServer } from 'node:http';
import { createCipheriv } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FIXTURES = resolve(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/hls',
);
const FIXTURES_DEMUXED = resolve(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/hls-demuxed',
);
const FIXTURES_PROGRESSIVE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/progressive',
);
/**
 * PACKAGE A — fMP4/CMAF bytes borrowed from the DASH fixture (committed, generated with
 * ffmpeg -f dash). Reused instead of generating a new fixture: this is REAL fMP4 packaged by
 * ffmpeg, and its video track gives exactly 100 frames — matching the FIXTURE_FRAMES constant
 * the e2e suite was already calibrated against.
 */
const FIXTURES_DASH_SRC = resolve(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/dash',
);

/**
 * W2.1 — session token generated by the page's "player". CANNOT be derived from URL/pageUrl/host,
 * so the extension can only obtain it by OBSERVING the player's real request (`onSendHeaders`).
 */
export const PLAYER_TOKEN = 'e2e-player-session-4f2a91';

/**
 * W2.1 debt (a) — a SECOND, distinct player token. Two HLS assets on the SAME host can each sit
 * behind their own token; this is the value the second asset's gate demands in the different-token
 * scenario. It must never be derivable from the first — the whole point is that mixing the two up
 * (one job clobbering the other's DNR header rule) is observable as a 403, not a silent wrong file.
 */
export const PLAYER_TOKEN_B = 'e2e-player-session-b-8c31d7';

/** Progressive mp4 file (read once) — used for the W2.5 case. */
const PROGRESSIVE_MP4 = readFileSync(join(FIXTURES_PROGRESSIVE, 'sample.mp4'));

/** Fixture content read once (small, 168KB). */
function readFixture(name) {
  return readFileSync(join(FIXTURES, name));
}

// --- W3.1 — AES-128 ENCRYPTED HLS -----------------------------------------------------------------
//
// WHY THIS EXISTS: AES-128 is the ONLY decryption branch this project is allowed to have (§7 —
// publicly served key, no access control bypassed), yet it has NEVER been touched by e2e across
// three sessions. The new pipeline (libav.js + OPFS) decrypts BEFORE writing to disk, so if this
// branch is broken the output file is garbage — and with garbage `av_write_trailer` still returns
// 0, exactly like the "missing moov but ffprobe exits 0" lesson.
//
// HOW IT'S PROVEN: the segments here are the SAME 10 plaintext segments from /hls/, encrypted in
// place. So the expectation exactly matches the calibrated `happy` case: **100 frames**. A wrong
// KEY produces random bytes, MPEG-TS loses sync, and there's no path to exactly 100 frames.
//
// Encrypted with `node:crypto` (OpenSSL) while the extension decrypts with WebCrypto -> TWO
// INDEPENDENT implementations, so there's no "same mistake on both sides" way for this case to go
// falsely green.
//
// 🔴 MEASURED LIMIT OF THIS CASE SET ITSELF — READ BEFORE TRUSTING IT COVERS MORE THAN IT DOES:
// The download cases here pin the KEY-FETCH path + CBC decryption, but **do NOT pin the IV-derivation
// path**. Measured via mutation on the real build (2026-07-19): swapping `seg.seq` for the array
// index -> case STAYS GREEN; ignoring `#EXT-X-KEY:IV=` -> case STAYS GREEN. Reason: it's a property
// of CBC — the IV only affects the FIRST 16-byte block of each segment. Measured on this very
// fixture: a wrong IV shifts EXACTLY 10 of 143,444 bytes, still 100 frames, IDENTICAL video-stream
// md5, EMPTY ffmpeg stderr, and the resulting .mp4 IDENTICAL BYTE-FOR-BYTE (verified with `cmp`).
// => NO content-based file assertion catches an IV bug with MPEG-TS. The net for IV lives in the
// unit test `utils/crypto.test.ts` (the "IV vector taken from this very e2e fixture" case), not
// here. Don't add a new e2e case hoping to catch IV bugs — already tried, doesn't work.
//
// 🔴 MEASURED (2026-07-19, don't re-measure) — utils/hls.ts + m3u8-parser@7.2.0:
//   - No IV declared -> `iv` ABSENT; IV = `seq` (ABSOLUTE media sequence) as 128-bit big-endian.
//   - `#EXT-X-MEDIA-SEQUENCE:7` -> the first segment has `seq = 7`, NOT 0.
//   - `IV=0x...` declared -> the parser returns a Uint32Array, utils converts it to exactly 16 bytes.
//   - Two `#EXT-X-KEY` tags -> each segment carries the correct `keyUri` for the group it belongs to.
//   - node aes-128-cbc + PKCS7 <-> `decryptAes128Cbc` match BYTE FOR BYTE (tested at ~18612 B, not a
//     multiple of 16).

/** FIXED 16-byte keys (deterministic so the e2e case is reproducible). Two different keys -> the key-rotation case. */
const AES_KEY_0 = Buffer.from('59564956494d2d6b65792d302d616573', 'hex');
const AES_KEY_1 = Buffer.from('59564956494d2d6b65792d312d616573', 'hex');

/**
 * Explicit IV — DELIBERATELY not all zeros and not equal to any IV derivable from `seq`.
 * ⚠️ This value is REUSED by the unit test as its expected vector; e2e CANNOT distinguish a
 * correct IV from a wrong one (see "MEASURED LIMIT" above). If you change this number, change it
 * in `utils/crypto.test.ts` too.
 */
const AES_EXPLICIT_IV = Buffer.from('a1b2c3d4e5f60718293a4b5c6d7e8f90', 'hex');

/**
 * MEDIA-SEQUENCE nonzero so `seq` does NOT coincide with the array index — this lets the unit test
 * distinguish a version using `seg.seq` from one that mistakenly uses the loop index.
 * ⚠️ Don't "tidy it back to 0", and don't assume e2e catches this: MEASURED, e2e does NOT catch it
 * (see "MEASURED LIMIT" above). What catches it is `utils/crypto.test.ts`.
 */
const AES_MEDIA_SEQUENCE = 7;

/** MEDIA-SEQUENCE of the explicit-IV playlist: nonzero so it's distinguishable from an IV derived from seq. */
const AES_IV_MEDIA_SEQUENCE = 3;

/** Segment index at which the second key starts being used (key-rotation case). */
const AES_ROTATE_AT = 5;

/** Default HLS IV: media sequence as 128-bit big-endian (12 zero bytes + uint32). */
function seqIv(seq) {
  const iv = Buffer.alloc(16);
  iv.writeUInt32BE(seq >>> 0, 12);
  return iv;
}

/** AES-128-CBC + PKCS7 — per the HLS spec (RFC 8216 §5.2). */
function aesEncrypt(plain, key, iv) {
  const c = createCipheriv('aes-128-cbc', key, iv);
  c.setAutoPadding(true);
  return Buffer.concat([c.update(plain), c.final()]);
}

/**
 * Three encrypted playlist variants, each with its OWN segment NAMESPACE (`seq`/`iv`/`rot`) because
 * the same plaintext segment is encrypted with a different IV/key in each variant.
 */
const AES_VARIANTS = {
  // Default IV (derived from seq) + MEDIA-SEQUENCE=7 -> pins the "IV from absolute seq" rule.
  seq: { mediaSequence: AES_MEDIA_SEQUENCE, explicitIv: false, rotate: false },
  // Explicit IV -> pins that `#EXT-X-KEY:IV=` is actually used.
  iv: { mediaSequence: AES_IV_MEDIA_SEQUENCE, explicitIv: true, rotate: false },
  // Two keys within one playlist -> pins that key caching does NOT smear the wrong key across the
  // whole stream.
  rot: { mediaSequence: 0, explicitIv: false, rotate: true },
  // Segment encrypted NORMALLY but the server serves the WRONG KEY (a different 16 bytes) ->
  // decryption throws. Real-world case: a CDN rotates the key but forgets to update it, or the key
  // URI points at a stale version.
  bad: { mediaSequence: 0, explicitIv: false, rotate: false, badKey: 'wrong' },
  // Server serves an HTML PAGE instead of the key (403/redirect to a login page — a VERY common
  // shape). This is the case where the key is NOT 16 bytes -> `importKey` throws, not a padding error.
  badlen: { mediaSequence: 0, explicitIv: false, rotate: false, badKey: 'html' },
};

/** WRONG 16-byte key (`bad` case) — correct length so it passes importKey, fails at unpadding. */
const AES_KEY_DECOY = Buffer.from('00112233445566778899aabbccddeeff', 'hex');

// --- W7.1/§7 — DRM PLAYLIST (hard boundary: MUST refuse, must not download) -----------------------
//
// 🔴 REAL VULNERABILITY MEASURED 2026-07-19: the three most common DRM systems SLIP PAST the §7
// boundary. m3u8-parser pushes a key with an unrecognized KEYFORMAT into `manifest.contentProtection`
// and does NOT set `segment.key`, so `parseHlsSegments` sees the DRM playlist as "unencrypted" ->
// isProtected=FALSE -> the extension downloads the full protected content. SAMPLE-AES only encrypts
// the NAL payload so the TS frames stay intact and libav remux SUCCEEDS -> the user gets a garbled
// .mp4 WITH A GREEN CHECKMARK.
//
// The segments here reuse the exact same regular segments: this case measures the REFUSAL DECISION,
// not decryption. If the guard is broken the job will run to completion and produce a file -> case
// goes RED. That is exactly what needs to be pinned.
const DRM_VARIANTS = {
  fairplay:
    '#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://key-id",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"',
  playready:
    '#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAA",KEYFORMAT="com.microsoft.playready"',
  widevine:
    '#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,AAAA",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"',
};

/** Media playlist declaring DRM, pointing at the SAME 10 regular segments from /hls/. */
function drmPlaylist(system) {
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:5',
    '#EXT-X-TARGETDURATION:1',
    '#EXT-X-MEDIA-SEQUENCE:0',
    DRM_VARIANTS[system],
  ];
  for (let i = 0; i < 10; i++) {
    lines.push('#EXTINF:1.0,', `http://127.0.0.1:__PORT__/hls/seg${i}.ts`);
  }
  lines.push('#EXT-X-ENDLIST', '');
  return lines.join('\n');
}

/** Key + IV for segment `i` in variant `name`. Single source of truth for both the playlist and the bytes. */
function aesParamsFor(name, i) {
  const v = AES_VARIANTS[name];
  const seq = v.mediaSequence + i;
  return {
    key: v.rotate && i >= AES_ROTATE_AT ? AES_KEY_1 : AES_KEY_0,
    iv: v.explicitIv ? AES_EXPLICIT_IV : seqIv(seq),
  };
}

/** Generate an encrypted media playlist for variant `name` (10 segments, matching /hls/media.m3u8). */
function aesPlaylist(name, keyHost, port) {
  const v = AES_VARIANTS[name];
  // `keyHost` puts the key on a DIFFERENT host than the manifest/segments. Necessary because DNR
  // rules are grouped BY HOST: if the key shared a host with the segments, the rule generated from
  // the segment URL would already cover the key too, so the "separate 403 gate for the key path"
  // case couldn't distinguish having vs. not having `add(s.keyUri)` in spoofTargets.
  // MEASURED: '127.0.0.1' and 'localhost' are TWO separate hosts to DNR (see top of file).
  const keyBase = keyHost ? `http://${keyHost}:${port}/hls-aes/${name}/` : '';
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:3',
    '#EXT-X-TARGETDURATION:1',
    `#EXT-X-MEDIA-SEQUENCE:${v.mediaSequence}`,
  ];
  for (let i = 0; i < 10; i++) {
    // #EXT-X-KEY is re-emitted exactly where the key changes; otherwise declared once up front (like a real CDN).
    if (i === 0 || (v.rotate && i === AES_ROTATE_AT)) {
      const keyFile =
        keyBase +
        (v.rotate && i >= AES_ROTATE_AT ? 'key1.bin' : 'key0.bin');
      const ivAttr = v.explicitIv
        ? `,IV=0x${AES_EXPLICIT_IV.toString('hex')}`
        : '';
      lines.push(`#EXT-X-KEY:METHOD=AES-128,URI="${keyFile}"${ivAttr}`);
    }
    lines.push('#EXTINF:1.0,', `seg${i}.ts`);
  }
  lines.push('#EXT-X-ENDLIST', '');
  return lines.join('\n');
}

// --- PACKAGE A — ENCRYPTED fMP4/CMAF HLS (#EXT-X-MAP + AES-128 covering init TOO) ----------------
//
// WHY THIS EXISTS: the 2026-07-20 session patched the "init segment (#EXT-X-MAP) not decrypted" gap
// per RFC 8216 §4.3.2.5 — but that patch had NO INSTRUMENT running to measure it, because the
// project had no encrypted fMP4 fixture. Every existing AES-128 case runs MPEG-TS, and TS has NO
// #EXT-X-MAP, so the init-decryption branch was never exercised.
//
// 🔴 WHY THIS FIXTURE HAS TEETH WHILE THE TS FIXTURE DOESN'T (the core difference, already measured
// in the AES-128 section above): with MPEG-TS, the IV only affects the FIRST 16 bytes of each
// segment, and those 16 bytes are just one TS packet — ffmpeg resyncs on its own, and the output
// file is IDENTICAL BYTE FOR BYTE. With fMP4, the first 16 bytes of the init are the `ftyp` header
// (size + magic), immediately followed by the `moov` describing the entire track. Corrupt that and
// there is NOTHING to resync: libav can't recognize the format and the job dies outright.
// => this is the ONLY place in the e2e suite where an init/IV-layer bug becomes OBSERVABLE.
//
// Bytes borrowed from e2e/fixtures/dash/ (generated with ffmpeg -f dash, committed): track 0 is
// h264 video, init-0.mp4 + chunk-0-00001..5.m4s = EXACTLY 100 frames / 10.0s — matching the `happy`
// case's expectation exactly, so the FIXTURE_FRAMES constant can be reused without recalibrating.
// Track 1 is aac audio.

/** Key for the fMP4 VIDEO stream. Different from all the TS keys above so there's no way to confuse keys between the two case sets. */
const FMP4_KEY_V = Buffer.from('59564956494d2d666d7034762d6b6579', 'hex');
/** SEPARATE key for the AUDIO stream — pins the "one #EXT-X-KEY per track" branch, never exercised before. */
const FMP4_KEY_A = Buffer.from('59564956494d2d666d7034612d6b6579', 'hex');

/**
 * EXPLICIT IV — RFC 8216 §4.3.2.5 REQUIRES declaring an IV when the key applies to the Media
 * Initialization Section, since the init has no sequence number to derive an IV from.
 * ⚠️ DELIBERATELY different from any IV derivable from `seq` (see FMP4_MEDIA_SEQUENCE): this way
 * the "ignore the explicit IV" mutation corrupts EXACTLY the first 16 bytes of the init = the
 * `ftyp` header -> case goes RED. On TS the same mutation leaves the case GREEN (already measured).
 * Don't change this value to 0 or to something that coincides with seq.
 */
const FMP4_EXPLICIT_IV = Buffer.from('7f3e1c0b9a8d6f4e2c1a0b9d8e7f6a5b', 'hex');

/**
 * MEDIA-SEQUENCE nonzero so the IV-derived-from-seq does NOT coincide with the explicit IV ->
 * mutations become distinguishable.
 * (For TS this detail is meaningless since e2e is blind to IV; for fMP4 it's exactly what gives it teeth.)
 */
const FMP4_MEDIA_SEQUENCE = 11;

/** Number of .m4s segments per fMP4 track (matches the count of chunk-N-* files in e2e/fixtures/dash). */
const FMP4_SEGMENTS = { v: 5, a: 6 };

/**
 * fMP4 variants:
 *   `plain` NOT encrypted -> the REVERSE case: guard against false-positive decryption/blocking.
 *   `enc`   AES-128 covers BOTH the init and the .m4s segments, explicit IV -> Package A's main case.
 *   `aud`   SEPARATE audio, each track with its OWN key -> the per-track keyCache branch, never
 *           exercised before.
 */
const FMP4_VARIANTS = {
  plain: { encrypted: false },
  enc: { encrypted: true },
  aud: { encrypted: true, demuxed: true },
  // 🔴 CLEAR INIT, ENCRYPTED SEGMENT — `#EXT-X-MAP` comes BEFORE `#EXT-X-KEY`.
  //
  // RFC 8216 §4.3.2.5 scopes keys by TAG POSITION: an `#EXT-X-KEY` covers the Media Initialization
  // Sections declared by any `#EXT-X-MAP` between it and the NEXT `#EXT-X-KEY`. So MAP coming
  // BEFORE the key means "clear init, encrypted segment" — a VALID and common playlist shape: a
  // clear init lets the player read the codec / initialize the decoder BEFORE requesting the key.
  //
  // 🔴 MEASURED (2026-07-20) — m3u8-parser@7.2.0 models this scoping CORRECTLY; our code was the
  // one that got it wrong:
  //     key BEFORE map -> segment.map.key = {method:'AES-128',...}
  //     map BEFORE key -> segment.map = {uri} and NO .key
  // The pre-patch version derived the init key from `segment.key` (the SEGMENT's key), so it
  // decrypted an init that was already clear -> WebCrypto threw a padding error -> the job died
  // with a message blaming the server: "key mismatch / server served the wrong key". A HEALTHY
  // stream killed by mistake — exactly the error class the project ranks worse than hanging. And
  // it's a REGRESSION: before the init-decryption patch, this shape downloaded fine.
  'clear-init': { encrypted: true, keyAfterMap: true },
};

/** Read raw fMP4 bytes from the DASH fixture. `track` is 'v' (0) or 'a' (1). */
function readFmp4(track, name) {
  const t = track === 'a' ? 1 : 0;
  const file =
    name === 'init'
      ? `init-${t}.mp4`
      : `chunk-${t}-${String(Number(name) + 1).padStart(5, '0')}.m4s`;
  return readFileSync(join(FIXTURES_DASH_SRC, file));
}

/** Key for a track in an fMP4 variant (separate audio -> two different keys). */
function fmp4Key(variant, track) {
  return FMP4_VARIANTS[variant].demuxed && track === 'a'
    ? FMP4_KEY_A
    : FMP4_KEY_V;
}

/**
 * fMP4 media playlist: `#EXT-X-MAP:URI="init.mp4"` + N `.m4s` segments.
 * When encrypted, `#EXT-X-KEY` is placed BEFORE `#EXT-X-MAP` — the tag order RFC requires for the
 * key to cover the init.
 */
function fmp4Playlist(variant, track) {
  const v = FMP4_VARIANTS[variant];
  const n = FMP4_SEGMENTS[track];
  const lines = [
    '#EXTM3U',
    '#EXT-X-VERSION:7',
    '#EXT-X-TARGETDURATION:2',
    `#EXT-X-MEDIA-SEQUENCE:${FMP4_MEDIA_SEQUENCE}`,
  ];
  // TAG ORDER IS SEMANTIC, NOT COSMETIC (RFC 8216 §4.3.2.5):
  //   KEY before MAP -> key covers init TOO  (variants `enc`, `aud`)
  //   MAP before KEY -> init is CLEAR        (variant `clear-init`)
  // Both are valid and both occur in the wild. Don't "tidy" these two branches into one.
  const keyLine = `#EXT-X-KEY:METHOD=AES-128,URI="key-${track}.bin",IV=0x${FMP4_EXPLICIT_IV.toString('hex')}`;
  if (v.encrypted && !v.keyAfterMap) lines.push(keyLine);
  lines.push(`#EXT-X-MAP:URI="init-${track}.mp4"`);
  if (v.encrypted && v.keyAfterMap) lines.push(keyLine);
  for (let i = 0; i < n; i++) {
    lines.push('#EXTINF:2.0,', `seg-${track}${i}.m4s`);
  }
  lines.push('#EXT-X-ENDLIST', '');
  return lines.join('\n');
}

/** Master for the SEPARATE-AUDIO variant: one playlist for video, one for audio, each with its own key. */
function fmp4Master() {
  return [
    '#EXTM3U',
    '#EXT-X-VERSION:7',
    '#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud",NAME="vi",LANGUAGE="vi",URI="media-a.m3u8"',
    '#EXT-X-STREAM-INF:BANDWIDTH=200000,RESOLUTION=128x96,CODECS="avc1.42c00d,mp4a.40.2",AUDIO="aud"',
    'media-v.m3u8',
    '',
  ].join('\n');
}

/**
 * @param {object} opts
 * @param {'none'|'manifest'|'segments'|'all'} [opts.gate] which path requires Referer (missing -> 403).
 * @param {string|null} [opts.segmentHost] if set, media.m3u8 returns ABSOLUTE segment URIs pointing
 *   at this host (builds the "segment on a different host than the manifest" case). Null -> relative
 *   URIs like a real manifest.
 * @param {string|null} [opts.keyHost] W3.1 — if set, the AES key URI is ABSOLUTE and points at this
 *   host (builds the "key lives on a different CDN host than the segments" case — a shape that's
 *   almost always true in the wild).
 * @param {boolean} [opts.stallSegments] W2.6 — the segment NEVER responds (keeps the socket open,
 *   completely silent). Simulates "network drops mid-download" / a hung server: this is the case
 *   where, before W2.6, the job would get stuck 'fetching' FOREVER, with no error, uncancelable,
 *   and jobChain would jam, dragging every subsequent job down with it.
 */
export async function startFixtureServer({
  gate = 'none',
  segmentHost = null,
  stallSegments = false,
  tokenGate = false,
  keyHost = null,
  // W2.1 debt (a) — two same-host HLS assets, each behind its own token. false = off; 'same' = both
  // slots demand PLAYER_TOKEN; 'different' = slot a demands PLAYER_TOKEN, slot b demands PLAYER_TOKEN_B.
  dualToken = false,
} = {}) {
  /** @type {{url:string, referer:string|undefined, token:string|undefined, status:number}[]} */
  const requests = [];

  const isSegment = (p) => /\/seg\d+\.ts$/.test(p);
  const isManifest = (p) => p.endsWith('.m3u8');
  const isProgressive = (p) => p === '/prog/sample.mp4';
  /**
   * W3.1 — the AES key is a SEPARATE fetch path (fetchWithRetry with a different label), not
   * sharing the segment path. The `key` gate isolates exactly that path: it proves the key fetch
   * ALSO gets the header replayed, rather than "the segment got through so the key must too".
   */
  const isAesKey = (p) => /^\/hls-aes\/\w+\/key\d\.bin$/.test(p);
  const needsReferer = (p) =>
    gate === 'all' ||
    (gate === 'manifest' && isManifest(p)) ||
    (gate === 'segments' && isSegment(p)) ||
    (gate === 'key' && isAesKey(p)) ||
    (gate === 'progressive' && isProgressive(p));

  const server = createServer((req, res) => {
    const path = (req.url ?? '/').split('?')[0];
    const referer = req.headers.referer;
    const token = req.headers['x-playback-session-id'];

    const send = (status, body, type) => {
      requests.push({ url: path, referer, token, status });
      res.writeHead(status, {
        'content-type': type,
        'cache-control': 'no-store',
      });
      res.end(body);
    };

    // Hotlink gate: NO Referer -> 403, just like a real anti-hotlink CDN.
    if (needsReferer(path) && !referer) {
      send(403, 'Forbidden: thiếu Referer', 'text/plain');
      return;
    }

    // W2.1 — TOKEN GATE: requires a header the extension CANNOT FABRICATE.
    //
    // Why this gate proves what Referer can't: Referer can be derived from pageUrl (the old FAKED
    // version did exactly that and still passed the gate). `X-Playback-Session-Id: <random value
    // generated by the page>` CANNOT be derived from anywhere — it can only be OBSERVED from the
    // player's real request. Passing this gate = the real header was captured & replayed. Not
    // passing = it wasn't.
    if (tokenGate && (isManifest(path) || isSegment(path))) {
      if (token !== PLAYER_TOKEN) {
        send(403, `Forbidden: token sai/thiếu (${token ?? 'NONE'})`, 'text/plain');
        return;
      }
    }

    // W2.1 debt (a) — PER-ASSET token gate. /hls-dual/<slot>/ demands the token registered for that
    // slot: slot a always wants PLAYER_TOKEN; slot b wants PLAYER_TOKEN_B only in 'different' mode.
    // A request arriving with the OTHER slot's token (one same-host job's DNR rule clobbered by the
    // other's) is a loud 403 here — never a silently wrong file.
    const dualSlot = /^\/hls-dual\/([ab])\//.exec(path);
    if (dualToken && dualSlot) {
      const want =
        dualSlot[1] === 'b' && dualToken === 'different'
          ? PLAYER_TOKEN_B
          : PLAYER_TOKEN;
      if (token !== want) {
        send(
          403,
          `Forbidden: token sai cho slot ${dualSlot[1]} (${token ?? 'NONE'})`,
          'text/plain',
        );
        return;
      }
    }

    // W3.1 — AES-128 ENCRYPTED HLS. Placed BEFORE the generic isSegment() branch: `/hls-aes/seq/seg0.ts`
    // also matches the segment regex, so falling through below would wrongly read the plaintext file
    // in e2e/fixtures/hls.
    const aesKey = /^\/hls-aes\/(\w+)\/key(\d)\.bin$/.exec(path);
    if (aesKey) {
      if (!AES_VARIANTS[aesKey[1]]) {
        send(404, 'biến thể AES không có', 'text/plain');
        return;
      }
      // HLS key served publicly over HTTP — just like a real CDN, and exactly where §7 draws the
      // boundary: there's no access control here to bypass.
      const badKey = AES_VARIANTS[aesKey[1]].badKey;
      if (badKey === 'wrong') {
        send(200, AES_KEY_DECOY, 'application/octet-stream');
        return;
      }
      if (badKey === 'html') {
        // 200 with HTML: the CDN redirects to a login page. Returning 200 is DELIBERATE — this
        // error is NOT caught at the fetch layer, it only surfaces at the key-construction step,
        // so it pins exactly the spot we need to pin.
        send(200, '<!doctype html><title>login</title>Vui lòng đăng nhập', 'text/html');
        return;
      }
      send(
        200,
        aesKey[2] === '1' ? AES_KEY_1 : AES_KEY_0,
        'application/octet-stream',
      );
      return;
    }
    const aesSeg = /^\/hls-aes\/(\w+)\/seg(\d+)\.ts$/.exec(path);
    if (aesSeg) {
      const [, variant, idx] = aesSeg;
      const i = Number(idx);
      if (!AES_VARIANTS[variant] || i < 0 || i > 9) {
        send(404, 'segment AES không có', 'text/plain');
        return;
      }
      const { key, iv } = aesParamsFor(variant, i);
      // The plaintext is the SAME segment as the `happy` case -> expect the output file to match exactly: 100 frames.
      send(200, aesEncrypt(readFixture(`seg${i}.bin`), key, iv), 'video/mp2t');
      return;
    }
    const drmPl = /^\/hls-drm\/(\w+)\/media\.m3u8$/.exec(path);
    if (drmPl) {
      if (!DRM_VARIANTS[drmPl[1]]) {
        send(404, 'hệ DRM không có', 'text/plain');
        return;
      }
      send(
        200,
        drmPlaylist(drmPl[1]).replaceAll('__PORT__', String(server.address().port)),
        'application/vnd.apple.mpegurl',
      );
      return;
    }

    const aesPl = /^\/hls-aes\/(\w+)\/media\.m3u8$/.exec(path);
    if (aesPl) {
      if (!AES_VARIANTS[aesPl[1]]) {
        send(404, 'biến thể AES không có', 'text/plain');
        return;
      }
      send(
        200,
        aesPlaylist(aesPl[1], keyHost, server.address().port),
        'application/vnd.apple.mpegurl',
      );
      return;
    }

    // --- PACKAGE A — fMP4/CMAF HLS (#EXT-X-MAP), encrypted or not with AES-128 ---
    //
    // Placed BEFORE all generic /hls/ branches: these paths use their own prefix so they don't
    // collide, but kept nearby for readability and to avoid repeating the "isSegment swallows the
    // AES path" lesson above. Variant names CAN contain a hyphen (`clear-init`) -> `[\w-]+`, don't
    // shrink it to `\w+`: getting this wrong makes the route 404 and the e2e case red for a reason
    // ENTIRELY UNRELATED to what it's meant to pin (already happened once).
    const fmp4 = /^\/hls-fmp4\/([\w-]+)\/([\w-]+)\.(m3u8|mp4|m4s|bin)$/.exec(path);
    if (fmp4) {
      const [, variant, name, ext] = fmp4;
      const v = FMP4_VARIANTS[variant];
      if (!v) {
        send(404, 'biến thể fMP4 không có', 'text/plain');
        return;
      }
      // Track's AES key (separate audio -> two different keys, which is what the `aud` variant pins).
      const keyM = /^key-([va])$/.exec(name);
      if (keyM && ext === 'bin') {
        send(200, fmp4Key(variant, keyM[1]), 'application/octet-stream');
        return;
      }
      if (name === 'master' && ext === 'm3u8') {
        send(200, fmp4Master(), 'application/vnd.apple.mpegurl');
        return;
      }
      const plM = /^media-([va])$/.exec(name);
      if (plM && ext === 'm3u8') {
        send(
          200,
          fmp4Playlist(variant, plM[1]),
          'application/vnd.apple.mpegurl',
        );
        return;
      }
      // init + segment: encrypted IN PLACE if the variant declares encryption. The IV is the
      // EXPLICIT IV for BOTH — per RFC 8216 §4.3.2.5 (a key covering the init must declare an IV,
      // since the init has no seq to derive one from).
      const initM = /^init-([va])$/.exec(name);
      const segM = /^seg-([va])(\d+)$/.exec(name);
      if ((initM && ext === 'mp4') || (segM && ext === 'm4s')) {
        const track = initM ? initM[1] : segM[1];
        if (segM && Number(segM[2]) >= FMP4_SEGMENTS[track]) {
          send(404, 'segment fMP4 không có', 'text/plain');
          return;
        }
        const plain = readFmp4(track, initM ? 'init' : segM[2]);
        // `keyAfterMap` -> the init is OUTSIDE the key's scope so it's served CLEAR, the segment is
        // still encrypted. This is the crux of the `clear-init` variant: the server tells the truth
        // per the RFC, and whichever side decrypts the init here is the side that's wrong.
        const encryptThis = v.encrypted && !(initM && v.keyAfterMap);
        const body = encryptThis
          ? aesEncrypt(plain, fmp4Key(variant, track), FMP4_EXPLICIT_IV)
          : plain;
        send(200, body, initM ? 'video/mp4' : 'video/iso.segment');
        return;
      }
      send(404, 'tài nguyên fMP4 không có', 'text/plain');
      return;
    }

    // W2.1 debt (a) — two HLS assets on the SAME host (slot a / slot b). Same muxable bytes as the
    // /hls/ set, just under a slot-scoped path so each carries its own token gate (checked above).
    // Placed BEFORE the generic isSegment() route, which slices a fixed '/hls/' prefix and would
    // read the wrong file for these paths. The relative `segN.ts` in media.m3u8 resolves under the
    // slot dir, so no rewrite is needed.
    const dual = /^\/hls-dual\/[ab]\/(media\.m3u8|seg(\d+)\.ts)$/.exec(path);
    if (dual) {
      if (dual[1] === 'media.m3u8') {
        send(200, readFixture('media.m3u8'), 'application/vnd.apple.mpegurl');
      } else {
        send(200, readFixture(`seg${dual[2]}.bin`), 'video/mp2t');
      }
      return;
    }

    if (path === '/hls/master.m3u8') {
      send(200, readFixture('master.m3u8'), 'application/vnd.apple.mpegurl');
      return;
    }
    if (path === '/hls/media.m3u8') {
      let text = readFixture('media.m3u8').toString('utf8');
      if (segmentHost) {
        // Point segments at a DIFFERENT host (same server, different hostname) -> pins §2.4.
        text = text.replace(
          /^(seg\d+\.ts)$/gm,
          (m) => `http://${segmentHost}:${server.address().port}/hls/${m}`,
        );
      }
      send(200, text, 'application/vnd.apple.mpegurl');
      return;
    }
    // W1.4 — THE SAME 10 segments as media.m3u8 but with #EXT-X-DISCONTINUITY tags inserted (the
    // exact shape of a stream with an ad break spliced in). Keeping the segment count identical is
    // DELIBERATE: the two playlists differ ONLY in whether the tag is present, so any observed
    // difference CANNOT come from anything else.
    //
    // 🔴 The second cluster is deliberately TWO ADJACENT TAGS (what a splicer emits for an empty ad
    // pod — a real-world shape). This lets the e2e case pin the COUNTING RULE too, not just the
    // pipeline: 3 tags / 2 splice points, so a naive `discontinuityStarts.length` count (MEASURED:
    // returns [4,7,7]) yields 3 and gets caught red-handed.
    if (path === '/hls/media-disc.m3u8') {
      send(200, readFixture('media-disc.m3u8'), 'application/vnd.apple.mpegurl');
      return;
    }
    // W2.6 — absolute stall: accept the request then go silent, no headers, no bytes, no socket close.
    if (stallSegments && isSegment(path)) {
      requests.push({ url: path, referer, status: 0 });
      req.socket.setKeepAlive(true);
      return; // NO res.end() -> the client needs its own timer to ever exit
    }
    if (isSegment(path)) {
      // The URL is .ts (the real HLS extension) but the file on disk is .bin — DELIBERATE, don't
      // "fix it to match": .ts COLLIDES with the TypeScript extension, so leaving it would make
      // tsc/eslint parse the video file as source code and turn the compile/lint gate RED. The
      // on-disk name is an internal detail; what the extension sees is the .ts URL + Content-Type
      // video/mp2t, so nothing is lost in realism.
      send(
        200,
        readFixture(path.slice('/hls/'.length).replace(/\.ts$/, '.bin')),
        'video/mp2t',
      );
      return;
    }
    // W2.7 — .mp4 ABSOLUTELY SILENT: accept the request then go quiet (no headers, no bytes, no
    // socket close). Used to hold a progressive download still long enough to kill offscreen mid-flight.
    if (path === '/prog/stall.mp4') {
      requests.push({ url: path, referer, status: 0 });
      req.socket.setKeepAlive(true);
      return; // NO res.end()
    }
    // W2.5 — progressive mp4 file. SUPPORTS Range (206) to exercise the offscreen byte-chunked path;
    // no Range returns 200 with the whole file (the body-stream path). Accept-Ranges tells the client it's allowed.
    if (isProgressive(path)) {
      const total = PROGRESSIVE_MP4.length;
      const range = req.headers.range;
      const m = range && /^bytes=(\d+)-(\d*)$/.exec(range);
      if (m) {
        const start = Number(m[1]);
        const end = m[2] ? Math.min(Number(m[2]), total - 1) : total - 1;
        if (start > end || start >= total) {
          requests.push({ url: path, referer, status: 416 });
          res.writeHead(416, { 'content-range': `bytes */${total}` });
          res.end();
          return;
        }
        requests.push({ url: path, referer, status: 206 });
        res.writeHead(206, {
          'content-type': 'video/mp4',
          'content-range': `bytes ${start}-${end}/${total}`,
          'content-length': end - start + 1,
          'accept-ranges': 'bytes',
          'cache-control': 'no-store',
        });
        res.end(PROGRESSIVE_MP4.subarray(start, end + 1));
        return;
      }
      requests.push({ url: path, referer, status: 200 });
      res.writeHead(200, {
        'content-type': 'video/mp4',
        'content-length': total,
        'accept-ranges': 'bytes',
        'cache-control': 'no-store',
      });
      res.end(PROGRESSIVE_MP4);
      return;
    }
    // W7.1 — a page SIMULATING DRM: requests EME just like Netflix/Disney+ do. There is NO real
    // protected content here — just an API call to prove the extension DETECTS it and REFUSES.
    if (path === '/drm.html') {
      send(
        200,
        `<!doctype html><title>drm fixture</title><p>drm page<script>
          navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{
            initDataTypes: ['cenc'],
            videoCapabilities: [{ contentType: 'video/mp4; codecs="avc1.42E01E"' }]
          }]).then(() => { window.__drmOk = true; }, () => { window.__drmOk = false; });
        </script>`,
        'text/html',
      );
      return;
    }
    // W2.1 — a page with a REAL "player": it fetches the manifest WITH its own token header. The
    // extension must be able to hear this fetch to have anything to replay.
    if (path === '/player.html') {
      send(
        200,
        `<!doctype html><title>player fixture</title><p>player page<script>
          window.__played = fetch('/hls/master.m3u8', {
            headers: { 'X-Playback-Session-Id': '${PLAYER_TOKEN}' },
          }).then((r) => r.text()).then(() => fetch('/hls/media.m3u8', {
            headers: { 'X-Playback-Session-Id': '${PLAYER_TOKEN}' },
          })).then((r) => r.ok);
        </script>`,
        'text/html',
      );
      return;
    }
    if (path === '/page.html') {
      send(
        200,
        '<!doctype html><title>fixture</title><p>fixture page',
        'text/html',
      );
      return;
    }
    // W2.1 debt (a) — player for one slot. It fetches ONLY that slot's media playlist, carrying the
    // token its gate demands, so the extension observes and stores the real header for that URL.
    // Slot b sends PLAYER_TOKEN_B only in 'different' mode (matching the gate above); otherwise the
    // same PLAYER_TOKEN as slot a.
    const dualPlayer = /^\/player-dual-([ab])\.html$/.exec(path);
    if (dualPlayer) {
      const slot = dualPlayer[1];
      const tok =
        slot === 'b' && dualToken === 'different'
          ? PLAYER_TOKEN_B
          : PLAYER_TOKEN;
      send(
        200,
        `<!doctype html><title>player dual ${slot}</title><p>player ${slot}<script>
          window.__played = fetch('/hls-dual/${slot}/media.m3u8', {
            headers: { 'X-Playback-Session-Id': '${tok}' },
          }).then((r) => r.ok);
        </script>`,
        'text/html',
      );
      return;
    }
    // W4.3 — child frame of /og.html. Both the title and og:title here are DELIBERATELY WRONG: if
    // the extension reads the title without pinning `frameIds: [0]`, it will grab these strings instead.
    if (path === '/og-frame.html') {
      send(
        200,
        '<!doctype html><title>JW Player</title>' +
          '<meta property="og:title" content="TIÊU ĐỀ IFRAME SAI">',
        'text/html; charset=utf-8',
      );
      return;
    }
    // W4.3 — a page with a CORRECT og:title while <title> is DIRTY (counter + site name).
    if (path === '/og.html') {
      send(
        200,
        '<!doctype html><title>(3) Tên Video Thật - Fixture Site</title>' +
          '<meta property="og:title" content="Tên Video Thật">' +
          '<meta name="twitter:title" content="TWITTER KHONG DUOC THANG OG">' +
          '<iframe src="/og-frame.html"></iframe>' +
          '<script>window.__m = fetch("/hls/master.m3u8").then(r => r.ok);</script>',
        'text/html; charset=utf-8',
      );
      return;
    }
    // W4.3 — NO meta tags at all: cleaning up <title> is the only way to get the correct name.
    if (path === '/doc.html') {
      send(
        200,
        '<!doctype html><title>(3) Tên Video Thật - 127.0.0.1</title>' +
          '<script>window.__m = fetch("/hls/master.m3u8").then(r => r.ok);</script>',
        'text/html; charset=utf-8',
      );
      return;
    }
    // W4.3 debt — ONLY twitter:title, NO og:title. og ALWAYS wins so the twitter:title-reading branch
    // in scripting.executeScript has never run in e2e; this page is the ONLY place that forces it to
    // run. <title> is dirty (counter + site name) to prove twitter wins over doc, not doc leaking through.
    if (path === '/twitter.html') {
      send(
        200,
        '<!doctype html><title>(9) KHÔNG DÙNG TITLE - Fixture Site</title>' +
          '<meta name="twitter:title" content="Tên Video Thật">' +
          '<script>window.__m = fetch("/hls/master.m3u8").then(r => r.ok);</script>',
        'text/html; charset=utf-8',
      );
      return;
    }
    send(404, 'not found', 'text/plain');
  });

  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;

  return {
    port,
    requests,
    origin: `http://127.0.0.1:${port}`,
    pageUrl: `http://127.0.0.1:${port}/page.html`,
    /** W2.1 — page with a player that sends its own token header. */
    playerPageUrl: `http://127.0.0.1:${port}/player.html`,
    /** W2.1 debt (a) — per-slot player pages + media URLs for the two same-host download scenario. */
    dualPlayerAUrl: `http://127.0.0.1:${port}/player-dual-a.html`,
    dualPlayerBUrl: `http://127.0.0.1:${port}/player-dual-b.html`,
    dualMediaAUrl: `http://127.0.0.1:${port}/hls-dual/a/media.m3u8`,
    dualMediaBUrl: `http://127.0.0.1:${port}/hls-dual/b/media.m3u8`,
    /** W7.1 — page that calls requestMediaKeySystemAccess (simulated DRM site). */
    drmPageUrl: `http://127.0.0.1:${port}/drm.html`,
    /** W4.3 — correct og:title + dirty <title> + iframe with a wrong title. */
    ogPageUrl: `http://127.0.0.1:${port}/og.html`,
    /** W4.3 — only a dirty <title>, no meta tags. */
    docPageUrl: `http://127.0.0.1:${port}/doc.html`,
    /** W4.3 debt — ONLY twitter:title (no og) -> forces the twitter-reading branch to run. */
    twitterPageUrl: `http://127.0.0.1:${port}/twitter.html`,
    masterUrl: `http://127.0.0.1:${port}/hls/master.m3u8`,
    mediaUrl: `http://127.0.0.1:${port}/hls/media.m3u8`,
    /** W1.4 — playlist identical to mediaUrl but with 2 splice points (ad-break stream). */
    discontinuityUrl: `http://127.0.0.1:${port}/hls/media-disc.m3u8`,
    /**
     * W3.1 — AES-128 ENCRYPTED playlist, same 10 plaintext segments as mediaUrl so the expected
     * output file MATCHES the `happy` case EXACTLY (100 frames). Three variants pin three different rules:
     *   `seq` IV derived from media sequence (MEDIA-SEQUENCE=7, offset from the array index);
     *   `iv`  explicit IV declared in #EXT-X-KEY;
     *   `rot` two keys within one playlist (switches at segment 5).
     */
    aesUrl: (variant) =>
      `http://127.0.0.1:${port}/hls-aes/${variant}/media.m3u8`,
    /** §7 — playlist declaring DRM (fairplay/playready/widevine). The extension MUST refuse, not download. */
    drmUrl: (system) => `http://127.0.0.1:${port}/hls-drm/${system}/media.m3u8`,
    /**
     * PACKAGE A — **fMP4/CMAF** HLS playlist (has `#EXT-X-MAP`). `track` defaults to 'v' (video).
     *   `plain` not encrypted   -> the reverse case;
     *   `enc`   AES-128 covers BOTH init and .m4s, explicit IV -> the main case;
     *   `aud`   separate audio, each track with its own key.
     */
    fmp4Url: (variant, track = 'v') =>
      `http://127.0.0.1:${port}/hls-fmp4/${variant}/media-${track}.m3u8`,
    /** PACKAGE A — master of the separate-audio variant (video + audio, two different keys). */
    fmp4MasterUrl: (variant) =>
      `http://127.0.0.1:${port}/hls-fmp4/${variant}/master.m3u8`,
    /**
     * Number of times the fMP4 init segment was served -> evidence the `#EXT-X-MAP` branch runs.
     * ⚠️ `[\w-]+`, NOT `\w+`: variant names contain a hyphen (`clear-init`). Using `\w+` makes the
     * counter always return 0 and the case fail for a reason entirely unrelated to what it's meant
     * to pin (already happened exactly once).
     */
    fmp4InitHits: () =>
      requests.filter((r) =>
        /^\/hls-fmp4\/[\w-]+\/init-[va]\.mp4$/.test(r.url),
      ).length,
    /** Number of fMP4 key fetches, split by track -> pins "each track fetches its own correct key". */
    fmp4KeyHits: (track) =>
      requests.filter((r) =>
        new RegExp(`^/hls-fmp4/[\\w-]+/key-${track ?? '[va]'}\\.bin$`).test(
          r.url,
        ),
      ).length,
    /** Number of /hls/ segments served -> if > 0 in a DRM case, it means the guard is BROKEN and real content was downloaded. */
    plainSegmentHits: () =>
      requests.filter((r) => /^\/hls\/seg\d+\.ts$/.test(r.url) && r.status < 400)
        .length,
    /** Number of times the AES key was actually served -> evidence the key-fetch path runs. */
    aesKeyHits: () =>
      requests.filter((r) => /^\/hls-aes\/\w+\/key\d\.bin$/.test(r.url)).length,
    /** W2.5 — progressive mp4 URL (127.0.0.1 host). */
    progressiveUrl: `http://127.0.0.1:${port}/prog/sample.mp4`,
    /** W2.7 — SILENT mp4 URL (server accepts then goes quiet) to hold a download still while killing offscreen. */
    stallProgressiveUrl: `http://127.0.0.1:${port}/prog/stall.mp4`,
    /** Number of progressive mp4 requests the server has SERVED (200/206) -> evidence bytes arrived. */
    progressiveHits: () =>
      requests.filter((r) => r.url === '/prog/sample.mp4' && r.status < 400)
        .length,
    /** Number of requests blocked with 403 -> evidence the gate fired. */
    blocked: () => requests.filter((r) => r.status === 403),
    close: () => new Promise((r) => server.close(r)),
  };
}

/**
 * **SEPARATE-AUDIO** HLS fixture server (master + SEPARATE video playlist + audio playlist).
 *
 * WHY SPLIT OUT FROM startFixtureServer: that fixture's master is **MUXED** (video+audio share the
 * same segment) — exactly the "easy case" §1.1 warns about, and the reason 193 tests were green
 * while the product was mute. This fixture has `#EXT-X-MEDIA:TYPE=AUDIO` + a variant pointing at
 * `AUDIO="aud-64000"`, i.e. EXACTLY the shape that produces downloads with no audio (§2.1) — the
 * shape Twitter/X, Vimeo, Twitch, and CMAF all use.
 *
 * Generated with ffmpeg (offline, deterministic, does NOT hit fMP4 bug #30 since this is MPEG-TS):
 *   video: testsrc 128x96, 10fps, 10s, -an -> 10 segments = 100 frames
 *   audio: sine 440Hz, 10s, aac 64k, -vn   -> 11 segments (audio segment count DIFFERS from video —
 *          matches reality, and catches any fix that silently assumes both sides have the same
 *          segment count).
 *
 * The master deliberately does NOT declare `DEFAULT` -> every rendition is `default=false` (a real
 * Twitter/X trap, already measured in W0.4): any fix relying solely on "prefer DEFAULT=YES" will
 * pick the wrong one and be exposed right here.
 */
export async function startDemuxedServer() {
  const FIXTURES_DASH = join(FIXTURES_DEMUXED, '..', 'dash');
  /** @type {{url:string, status:number}[]} */
  const requests = [];

  const server = createServer((req, res) => {
    const path = (req.url ?? '/').split('?')[0];
    const send = (status, body, type) => {
      requests.push({ url: path, status });
      res.writeHead(status, {
        'content-type': type,
        'cache-control': 'no-store',
      });
      res.end(body);
    };

    // .ts extension in the URL (the real HLS extension) but the file on disk is .bin — same reason
    // as the muxed fixture: .ts collides with the TypeScript extension so tsc/eslint would parse the
    // video file as source code (already paid for this at W0.3).
    const m = /^\/hls\/((?:v|a)\d+)\.ts$/.exec(path);
    if (m) {
      send(
        200,
        readFileSync(join(FIXTURES_DEMUXED, `${m[1]}.bin`)),
        'video/mp2t',
      );
      return;
    }
    // W1.5 — a REAL DASH fixture (ffmpeg -f dash): separate audio, fMP4, SegmentTemplate — the most
    // common shape in the wild. Video Representation id="0", audio id="1".
    const d = /^\/dash\/([\w.-]+\.(?:mpd|m4s|mp4))$/.exec(path);
    if (d) {
      const type = d[1].endsWith('.mpd')
        ? 'application/dash+xml'
        : d[1].endsWith('.m4s')
          ? 'video/iso.segment'
          : 'video/mp4';
      send(200, readFileSync(join(FIXTURES_DASH, d[1])), type);
      return;
    }
    const pl = /^\/hls\/(master|video|audio)\.m3u8$/.exec(path);
    if (pl) {
      send(
        200,
        readFileSync(join(FIXTURES_DEMUXED, `${pl[1]}.m3u8`)),
        'application/vnd.apple.mpegurl',
      );
      return;
    }
    // W7.1 — a page SIMULATING DRM: requests EME just like Netflix/Disney+ do. There is NO real
    // protected content here — just an API call to prove the extension DETECTS it and REFUSES.
    if (path === '/drm.html') {
      send(
        200,
        `<!doctype html><title>drm fixture</title><p>drm page<script>
          navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{
            initDataTypes: ['cenc'],
            videoCapabilities: [{ contentType: 'video/mp4; codecs="avc1.42E01E"' }]
          }]).then(() => { window.__drmOk = true; }, () => { window.__drmOk = false; });
        </script>`,
        'text/html',
      );
      return;
    }
    if (path === '/page.html') {
      send(
        200,
        '<!doctype html><title>fixture tách tiếng</title><p>fixture',
        'text/html',
      );
      return;
    }
    send(404, 'not found', 'text/plain');
  });

  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;

  return {
    port,
    requests,
    origin: `http://127.0.0.1:${port}`,
    pageUrl: `http://127.0.0.1:${port}/page.html`,
    /** W7.1 — page that calls requestMediaKeySystemAccess (simulated DRM site). */
    drmPageUrl: `http://127.0.0.1:${port}/drm.html`,
    /** W1.5 — DASH manifest (video + audio live in the SAME file, distinguished by Representation@id). */
    mpdUrl: `http://127.0.0.1:${port}/dash/stream.mpd`,
    /** Whether a DASH segment has been fetched yet -> evidence the DASH path actually runs. */
    dashSegmentHits: () =>
      requests.filter((r) => /\/chunk-\d+-\d+\.m4s$/.test(r.url)).length,
    dashAudioHits: () =>
      requests.filter((r) => /\/chunk-1-\d+\.m4s$/.test(r.url)).length,
    masterUrl: `http://127.0.0.1:${port}/hls/master.m3u8`,
    /** VIDEO playlist — what the user selects when clicking 720p (it does NOT contain audio). */
    videoUrl: `http://127.0.0.1:${port}/hls/video.m3u8`,
    audioUrl: `http://127.0.0.1:${port}/hls/audio.m3u8`,
    /** Whether an audio segment has been fetched yet -> evidence the audio path actually runs. */
    audioSegmentHits: () =>
      requests.filter((r) => /\/a\d+\.ts$/.test(r.url)).length,
    close: () => new Promise((r) => server.close(r)),
  };
}
