// Rebuild the libav.js `ts2mp4d` variant from source and place the output into vendor/libav/.
//
// Normally there is NO need to run this script: the output is already committed under public/libav/.
// Only run it when upgrading libav.js or changing the component list — and when that happens,
// the new binary must be committed along with an updated public/libav/BUILD.md.
//
// LGPL-2.1 obligation: this script IS "the scripts used to control compilation" that the
// license requires to be published alongside the binary. Don't delete it just because no one runs it day to day.

import { execFileSync } from 'node:child_process';
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'public/libav');

const VARIANT = 'ts2mp4d';
const LIBAV_VER = '6.9.8.1';

// Keep IN SYNC with public/libav/config.json. Both places must match, and
// scripts/libav-vendor.test.ts locks that in.
const COMPONENTS = [
  'avformat',
  'avcodec',
  // REQUIRED: without this fragment, bsf gets compiled into libavcodec but does NOT
  // export any av_bsf_* function to JS -> calling it is undefined.
  'avbsf',
  'demuxer-mpegts',
  'format-mp4',
  'parser-h264',
  'parser-aac',
  // REQUIRED even though we only stream-copy: without it avformat_find_stream_info can't
  // determine sample_rate/channels for AAC -> the mp4 muxer dies with "sample rate not set".
  'decoder-aac',
  'bsf-extract_extradata',
  'bsf-aac_adtstoasc',
  'bsf-h264_mp4toannexb',
];

const srcDir = process.env.LIBAV_SRC;
if (!srcDir || !existsSync(srcDir)) {
  console.error(
    [
      '[build-libav] Cần mã nguồn libav.js.',
      '',
      '  1) Tải tarball npm và giải nén:  npm pack libav.js@6.9.8 && tar xzf libav.js-6.9.8.tgz',
      '  2) Giải nén tiếp package/sources/libav.js.tar.xz để lấy cây nguồn',
      '  3) Chạy lại với:  LIBAV_SRC=/đường/dẫn/tới/libav.js pnpm build:libav',
      '',
      'Cần sẵn emsdk 6.0.3 đã activate (emcc phải nằm trong PATH).',
    ].join('\n'),
  );
  process.exit(1);
}

try {
  execFileSync('emcc', ['--version'], { stdio: 'pipe' });
} catch {
  console.error(
    '[build-libav] Không thấy `emcc`. Cài emsdk rồi `source ./emsdk_env.sh`.',
  );
  process.exit(1);
}

// 🔴 macOS trap: mk/ffmpeg.mk passes --ranlib=emranlib but FORGETS --ar=emar, so configure
// picks up Apple's `ar`. It silently creates an empty 96-byte archive, and the error only
// surfaces at link time as dozens of "wasm-ld: symbol exported via --export not found" lines.
// Prepend an ar -> emar shim to PATH to avoid this. Not needed on Linux/CI but harmless there.
const shimDir = resolve(root, 'node_modules/.cache/libav-arfix');
mkdirSync(shimDir, { recursive: true });
const shim = resolve(shimDir, 'ar');
writeFileSync(shim, '#!/bin/sh\nexec emar "$@"\n');
chmodSync(shim, 0o755);
const env = { ...process.env, PATH: `${shimDir}:${process.env.PATH ?? ''}` };

console.log(`[build-libav] Khai báo variant ${VARIANT}...`);
execFileSync('node', ['./mkconfig.js', VARIANT, JSON.stringify(COMPONENTS)], {
  cwd: srcDir,
  env,
  stdio: 'inherit',
});

// Build both the wasm and the ESM entry. The ESM entry (.mjs) is NOT generated by default
// for a self-declared variant — without it, offscreen can't import it, the exact UMD/ESM
// trap that killed the project once already with @ffmpeg/core.
for (const target of [
  `dist/libav-${LIBAV_VER}-${VARIANT}.wasm.mjs`,
  `dist/libav-${LIBAV_VER}-${VARIANT}.mjs`,
]) {
  console.log(`[build-libav] make ${target}`);
  execFileSync('make', ['-j8', target], { cwd: srcDir, env, stdio: 'inherit' });
}

mkdirSync(outDir, { recursive: true });
const artifacts = [
  `libav-${LIBAV_VER}-${VARIANT}.mjs`,
  `libav-${LIBAV_VER}-${VARIANT}.wasm.mjs`,
  `libav-${LIBAV_VER}-${VARIANT}.wasm.wasm`,
];
for (const f of artifacts) {
  copyFileSync(resolve(srcDir, 'dist', f), resolve(outDir, f));
  console.log(`[build-libav] ${f} -> public/libav/`);
}
copyFileSync(
  resolve(srcDir, `configs/configs/${VARIANT}/config.json`),
  resolve(outDir, 'config.json'),
);

console.log(
  '[build-libav] Xong. Nhớ commit lại public/libav/ và cập nhật BUILD.md.',
);
